apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fcm23ex3b-go
  janus-idp.io/tekton: fcm23ex3b-go
  backstage.io/kubernetes-id: fcm23ex3b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fcm23ex3b-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
